import type { Application, DashboardStat } from "@/types/application";

export const dashboardStats = [
  {
    label: "Candidaturas",
    value: 24,
    change: "+18,2 %",
    changeLabel: "frente al mes anterior",
    helperText: "Candidaturas activas en tu proceso",
    icon: "briefcase",
  },
  {
    label: "Entrevistas",
    value: 6,
    change: "+12,5 %",
    changeLabel: "frente al mes anterior",
    helperText: "Conversaciones previstas este mes",
    icon: "calendar",
  },
  {
    label: "Ofertas",
    value: 2,
    change: "+1",
    changeLabel: "este mes",
    helperText: "Ofertas recibidas en tus candidaturas",
    icon: "sparkle",
  },
  {
    label: "Rechazos",
    value: 8,
    change: "-9,4 %",
    changeLabel: "frente al mes anterior",
    helperText: "Una tasa menor que el mes anterior",
    icon: "x-circle",
  },
] satisfies readonly DashboardStat[];

export const applications = [
  {
    id: "app-linear",
    company: "Linear",
    companyInitials: "L",
    position: "Diseñador/a de producto sénior",
    status: "interview",
    location: "Madrid, España",
    workMode: "hybrid",
    appliedAt: "2026-08-22",
    technologies: ["Figma", "FigJam", "User research"],
  },
  {
    id: "app-vercel",
    company: "Vercel",
    companyInitials: "V",
    position: "Ingeniero/a frontend",
    status: "applied",
    location: "Remoto",
    workMode: "remote",
    appliedAt: "2026-08-21",
    technologies: ["React", "TypeScript", "Next.js"],
  },
  {
    id: "app-notion",
    company: "Notion",
    companyInitials: "N",
    position: "Responsable de producto",
    status: "offer",
    location: "Londres, Reino Unido",
    workMode: "onsite",
    appliedAt: "2026-08-18",
    technologies: ["Product strategy", "SQL", "Analytics"],
  },
  {
    id: "app-ramp",
    company: "Ramp",
    companyInitials: "R",
    position: "Diseñador/a UX sénior",
    status: "rejected",
    location: "Nueva York, Estados Unidos",
    workMode: "hybrid",
    appliedAt: "2026-08-16",
    technologies: ["Figma", "Prototyping", "Design systems"],
  },
  {
    id: "app-figma",
    company: "Figma",
    companyInitials: "F",
    position: "Ingeniero/a de diseño",
    status: "technical_test",
    location: "San Francisco, Estados Unidos",
    workMode: "remote",
    appliedAt: "2026-08-14",
    technologies: ["React", "TypeScript", "CSS"],
  },
  {
    id: "app-stripe",
    company: "Stripe",
    companyInitials: "S",
    position: "Ingeniero/a de software",
    status: "applied",
    location: "Dublín, Irlanda",
    workMode: "hybrid",
    appliedAt: "2026-08-12",
    technologies: ["Node.js", "TypeScript", "PostgreSQL"],
  },
  {
    id: "app-github",
    company: "GitHub",
    companyInitials: "G",
    position: "Diseñador/a de producto",
    status: "interview",
    location: "Remoto",
    workMode: "remote",
    appliedAt: "2026-08-10",
    technologies: ["Figma", "Accessibility", "Design systems"],
  },
  {
    id: "app-airbnb",
    company: "Airbnb",
    companyInitials: "A",
    position: "Ingeniero/a frontend",
    status: "technical_test",
    location: "Barcelona, España",
    workMode: "onsite",
    appliedAt: "2026-08-07",
    technologies: ["React", "GraphQL", "Testing"],
  },
] satisfies readonly Application[];

export const recentApplications = applications.slice(0, 5);
