import type { Application, DashboardStat } from "@/types/application";

export const dashboardStats = [
  {
    label: "Candidaturas",
    value: 24,
    change: "+18,2 %",
    changeLabel: "frente al mes anterior",
    helperText: "Candidaturas activas en tu proceso",
    icon: "briefcase",
  },
  {
    label: "Entrevistas",
    value: 6,
    change: "+12,5 %",
    changeLabel: "frente al mes anterior",
    helperText: "Conversaciones previstas este mes",
    icon: "calendar",
  },
  {
    label: "Ofertas",
    value: 2,
    change: "+1",
    changeLabel: "este mes",
    helperText: "Ofertas recibidas en tus candidaturas",
    icon: "sparkle",
  },
  {
    label: "Rechazos",
    value: 8,
    change: "-9,4 %",
    changeLabel: "frente al mes anterior",
    helperText: "Una tasa menor que el mes anterior",
    icon: "x-circle",
  },
] satisfies readonly DashboardStat[];

export const recentApplications = [
  {
    id: "app-linear",
    company: "Linear",
    companyInitials: "L",
    role: "Diseñador/a de producto sénior",
    status: "Entrevista",
    appliedAt: "2026-08-22",
    appliedLabel: "22 ago. 2026",
    logoTone: "blue",
  },
  {
    id: "app-vercel",
    company: "Vercel",
    companyInitials: "V",
    role: "Ingeniero/a frontend",
    status: "Enviada",
    appliedAt: "2026-08-21",
    appliedLabel: "21 ago. 2026",
    logoTone: "violet",
  },
  {
    id: "app-notion",
    company: "Notion",
    companyInitials: "N",
    role: "Responsable de producto",
    status: "Oferta",
    appliedAt: "2026-08-18",
    appliedLabel: "18 ago. 2026",
    logoTone: "amber",
  },
  {
    id: "app-ramp",
    company: "Ramp",
    companyInitials: "R",
    role: "Diseñador/a UX sénior",
    status: "Rechazada",
    appliedAt: "2026-08-16",
    appliedLabel: "16 ago. 2026",
    logoTone: "rose",
  },
  {
    id: "app-figma",
    company: "Figma",
    companyInitials: "F",
    role: "Ingeniero/a de diseño",
    status: "Enviada",
    appliedAt: "2026-08-14",
    appliedLabel: "14 ago. 2026",
    logoTone: "emerald",
  },
] satisfies readonly Application[];
